### ISSUE TITLE
The gui text on linux is too big

### ISSUE THREAD

**Issue by lowy** [z-------------/CPod#115]
**CPod version:**
1.27.0-444
**Description:**
![_google-chrome_20181031170902](https://user-images.githubusercontent.com/6565177/47777761-635ce080-dd30-11e8-8b80-5dc3d62a7551.png)

**Comment by z-------------** [comment]
Those are actually supposed to be icons, and I'm not sure why they're displaying as text — I haven't had this problem in my Linux testing.

Could you open Developer tools (`Ctrl-Shift-I`), activate the element selector (`Ctrl-Shift-C`), click on any of the big text that should be icon, click on "Computed" in the sidebar, scroll to the bottom and tell me what it says under "Rendered Fonts"? That might help me figure this bug out.

**Comment by lowy** [comment]
Sorry, I don't know what's the developer tools. So I don't know how to submit bug. I print CPod message on the terminal,  I hope to help you.
sysytem:  Debian testing x64
CPod: 1.27.0-444 deb

$> cpod
Checking for update
Error: Error: ENOENT: no such file or directory, open '/opt/CPod/resources/app-update.yml'
    at /opt/CPod/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:370:27
    at Generator.next (<anonymous>)
From previous event:
    at AppImageUpdater.loadUpdateConfig (/opt/CPod/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:395:11)
    at Lazy.AppUpdater.configOnDisk.Lazy (/opt/CPod/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:132:43)
    at Lazy.get value [as value] (/opt/CPod/resources/app.asar/node_modules/lazy-val/src/main.ts:18:23)
    at /opt/CPod/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:281:46
    at Generator.next (<anonymous>)
From previous event:
    at AppImageUpdater.doCheckForUpdates (/opt/CPod/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:353:11)
    at /opt/CPod/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:264:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at AppImageUpdater._checkForUpdates (/opt/CPod/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:307:11)
    at AppImageUpdater.checkForUpdates (/opt/CPod/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:213:35)
    at Object.<anonymous> (/opt/CPod/resources/app.asar/main.js:142:13)
    at Object.<anonymous> (/opt/CPod/resources/app.asar/main.js:256:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Object.<anonymous> (/opt/CPod/resources/electron.asar/browser/init.js:186:8)
    at Object.<anonymous> (/opt/CPod/resources/electron.asar/browser/init.js:188:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Function.Module.runMain (module.js:683:10)
    at startup (bootstrap_node.js:196:16)
    at bootstrap_node.js:622:3
There was a problem updating the application
{ Error: ENOENT: no such file or directory, open '/opt/CPod/resources/app-update.yml'
    at /opt/CPod/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:370:27
    at Generator.next (<anonymous>)
From previous event:
    at AppImageUpdater.loadUpdateConfig (/opt/CPod/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:395:11)
    at Lazy.AppUpdater.configOnDisk.Lazy (/opt/CPod/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:132:43)
    at Lazy.get value [as value] (/opt/CPod/resources/app.asar/node_modules/lazy-val/src/main.ts:18:23)
    at /opt/CPod/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:281:46
    at Generator.next (<anonymous>)
From previous event:
    at AppImageUpdater.doCheckForUpdates (/opt/CPod/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:353:11)
    at /opt/CPod/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:264:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at AppImageUpdater._checkForUpdates (/opt/CPod/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:307:11)
    at AppImageUpdater.checkForUpdates (/opt/CPod/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:213:35)
    at Object.<anonymous> (/opt/CPod/resources/app.asar/main.js:142:13)
    at Object.<anonymous> (/opt/CPod/resources/app.asar/main.js:256:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Object.<anonymous> (/opt/CPod/resources/electron.asar/browser/init.js:186:8)
    at Object.<anonymous> (/opt/CPod/resources/electron.asar/browser/init.js:188:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Function.Module.runMain (module.js:683:10)
    at startup (bootstrap_node.js:196:16)
    at bootstrap_node.js:622:3
  cause: 
   { Error: ENOENT: no such file or directory, open '/opt/CPod/resources/app-update.yml'
     errno: -2,
     code: 'ENOENT',
     syscall: 'open',
     path: '/opt/CPod/resources/app-update.yml' },
  isOperational: true,
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/opt/CPod/resources/app-update.yml' }
Unhandled rejection Error: ENOENT: no such file or directory, open '/opt/CPod/resources/app-update.yml'
    at /opt/CPod/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:370:27
    at Generator.next (<anonymous>)
From previous event:
    at AppImageUpdater.loadUpdateConfig (/opt/CPod/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:395:11)
    at Lazy.AppUpdater.configOnDisk.Lazy (/opt/CPod/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:132:43)
    at Lazy.get value [as value] (/opt/CPod/resources/app.asar/node_modules/lazy-val/src/main.ts:18:23)
    at /opt/CPod/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:281:46
    at Generator.next (<anonymous>)
From previous event:
    at AppImageUpdater.doCheckForUpdates (/opt/CPod/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:353:11)
    at /opt/CPod/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:264:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at AppImageUpdater._checkForUpdates (/opt/CPod/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:307:11)
    at AppImageUpdater.checkForUpdates (/opt/CPod/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:213:35)
    at Object.<anonymous> (/opt/CPod/resources/app.asar/main.js:142:13)
    at Object.<anonymous> (/opt/CPod/resources/app.asar/main.js:256:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Object.<anonymous> (/opt/CPod/resources/electron.asar/browser/init.js:186:8)
    at Object.<anonymous> (/opt/CPod/resources/electron.asar/browser/init.js:188:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Function.Module.runMain (module.js:683:10)
    at startup (bootstrap_node.js:196:16)
    at bootstrap_node.js:622:3

Failed to encode dictionary
Failed to encode reply value

**Comment by ben2talk** [comment]
I have this issue.
I installed Cpod last month, it worked fine. After reinstalling my system, I reinstalled Cpod (AUR build).
Icons replaced with huge text...

I removed the cpod-git build, downloaded the appimage and have the SAME issue.
Now my terminal is building cpod.

I saw your request "Could you open Developer tools (Ctrl-Shift-I), activate the element selector (Ctrl-Shift-C)"

I'm sorry, but Ctrl-Shift-I does not open Developer tools. Can you explain?
