### ISSUE TITLE
Error in Update Episodes

### ISSUE THREAD

**Issue by vinimmelo** [z-------------/CPod#143]
**CPod version: CPod v1.27.1**

**Platform: Linux (Manjaro)**

**Install type (.deb, Snap, etc.): Pacman**

**Description:**
- Problem with update of episodes.

**Did the bug only appear after a CPod update? Version before, after:**
After reboot/update
**Steps to reproduce:**
When open the CPod, auto update won't fully update, the bar not complete.

**Other helpful information (e.g. Developer Tools console log, screenshots) if possible:**
Stack Trace:

Checking for update
Error: Error: ENOENT: no such file or directory, open '/opt/CPod/resources/app-update.yml'
    at /opt/CPod/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:370:27
    at Generator.next (<anonymous>)
From previous event:
    at AppImageUpdater.loadUpdateConfig (/opt/CPod/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:395:11)
    at Lazy.AppUpdater.configOnDisk.Lazy (/opt/CPod/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:132:43)
    at Lazy.get value [as value] (/opt/CPod/resources/app.asar/node_modules/lazy-val/src/main.ts:18:23)
    at /opt/CPod/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:281:46
    at Generator.next (<anonymous>)
From previous event:
    at AppImageUpdater.doCheckForUpdates (/opt/CPod/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:353:11)
    at /opt/CPod/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:264:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at AppImageUpdater._checkForUpdates (/opt/CPod/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:307:11)
    at AppImageUpdater.checkForUpdates (/opt/CPod/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:213:35)
    at Object.<anonymous> (/opt/CPod/resources/app.asar/main.js:241:13)
    at Object.<anonymous> (/opt/CPod/resources/app.asar/main.js:357:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Object.<anonymous> (/opt/CPod/resources/electron.asar/browser/init.js:186:8)
    at Object.<anonymous> (/opt/CPod/resources/electron.asar/browser/init.js:188:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Function.Module.runMain (module.js:683:10)
    at startup (bootstrap_node.js:196:16)
    at bootstrap_node.js:622:3
auto-update error
{ Error: ENOENT: no such file or directory, open '/opt/CPod/resources/app-update.yml'
    at /opt/CPod/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:370:27
    at Generator.next (<anonymous>)
From previous event:
    at AppImageUpdater.loadUpdateConfig (/opt/CPod/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:395:11)
    at Lazy.AppUpdater.configOnDisk.Lazy (/opt/CPod/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:132:43)
    at Lazy.get value [as value] (/opt/CPod/resources/app.asar/node_modules/lazy-val/src/main.ts:18:23)
    at /opt/CPod/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:281:46
    at Generator.next (<anonymous>)
From previous event:
    at AppImageUpdater.doCheckForUpdates (/opt/CPod/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:353:11)
    at /opt/CPod/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:264:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at AppImageUpdater._checkForUpdates (/opt/CPod/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:307:11)
    at AppImageUpdater.checkForUpdates (/opt/CPod/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:213:35)
    at Object.<anonymous> (/opt/CPod/resources/app.asar/main.js:241:13)
    at Object.<anonymous> (/opt/CPod/resources/app.asar/main.js:357:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Object.<anonymous> (/opt/CPod/resources/electron.asar/browser/init.js:186:8)
    at Object.<anonymous> (/opt/CPod/resources/electron.asar/browser/init.js:188:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Function.Module.runMain (module.js:683:10)
    at startup (bootstrap_node.js:196:16)
    at bootstrap_node.js:622:3
  cause: 
   { Error: ENOENT: no such file or directory, open '/opt/CPod/resources/app-update.yml'
     errno: -2,
     code: 'ENOENT',
     syscall: 'open',
     path: '/opt/CPod/resources/app-update.yml' },
  isOperational: true,
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/opt/CPod/resources/app-update.yml' }
Unhandled rejection Error: ENOENT: no such file or directory, open '/opt/CPod/resources/app-update.yml'
    at /opt/CPod/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:370:27                                            
    at Generator.next (<anonymous>)                                                                                                   
From previous event:                                                                                                                  
    at AppImageUpdater.loadUpdateConfig (/opt/CPod/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:395:11)
    at Lazy.AppUpdater.configOnDisk.Lazy (/opt/CPod/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:132:43)
    at Lazy.get value [as value] (/opt/CPod/resources/app.asar/node_modules/lazy-val/src/main.ts:18:23)
    at /opt/CPod/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:281:46
    at Generator.next (<anonymous>)
From previous event:
    at AppImageUpdater.doCheckForUpdates (/opt/CPod/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:353:11)
    at /opt/CPod/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:264:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at AppImageUpdater._checkForUpdates (/opt/CPod/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:307:11)
    at AppImageUpdater.checkForUpdates (/opt/CPod/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:213:35)
    at Object.<anonymous> (/opt/CPod/resources/app.asar/main.js:241:13)
    at Object.<anonymous> (/opt/CPod/resources/app.asar/main.js:357:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Object.<anonymous> (/opt/CPod/resources/electron.asar/browser/init.js:186:8)
    at Object.<anonymous> (/opt/CPod/resources/electron.asar/browser/init.js:188:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Function.Module.runMain (module.js:683:10)
    at startup (bootstrap_node.js:196:16)
    at bootstrap_node.js:622:3

**Comment by z-------------** [comment]
Usually this type of bug is caused by some kind of RSS parse error; would it be possible for you to attach here (or email me) screenshots of any errors shown in the Developer Tools console and/or a list of podcasts you are subscribed to? Thanks.

**Comment by vinimmelo** [comment]
> Usually this type of issue is caused by some kind of RSS parse error; would it be possible for you to attach here (or email me) screenshots of any errors shown in the Developer Tools console (CPod settings -> scroll to bottom -> Open Developer Tools -> Console) and/or a list of podcasts you are subscribed to? Thanks.

THis error disappear after two reboots of the system, i don't know if will appear again, please close the issue.
