### ISSUE TITLE
Impossible to compile sources of CPOD.

### ISSUE THREAD

**Issue by e471wo** [z-------------/CPod#240]
**CPod version:**
last (github clone)
**Platform:**
mac os
**Installation type (.deb, Snap, etc.):**
yarn... I try to compile
**Description:**
I cloned the gihub and , as it say, made a yarn.  but I have this message
warning ../../../package.json: No license field

[1/4] 🔍  Resolving packages...
⠁ 

[2/4] 🚚  Fetching packages...
[##################--------------------------------------------------------------------------------------------------------------------------] 135/1028
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
[1/4] ⡀ fsevents
[2/4] ⡀ electron
[3/4] ⡀ node-sass
warning Error running install script for optional dependency: "/Users/elekis/Desktop/Github/CPod/node_modules/dbus: Command failed.
Exit code: 1
Command: node-gyp configure build
Arguments: 
Directory: /Users/elekis/Desktop/Github/CPod/node_modules/dbus
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@8.4.0
gyp info using node@14.15.1 | darwin | x64
gyp info find Python using Python version 3.9.9 found at \"/usr/local/opt/python@3.9/bin/python3.9\"
gyp info spawn /usr/local/opt/python@3.9/bin/python3.9
gyp info spawn args [
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/elekis/Desktop/Github/CPod/node_modules/dbus/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/elekis/Library/Caches/node-gyp/14.15.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/elekis/Library/Caches/node-gyp/14.15.1',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/elekis/Library/Caches/node-gyp/14.15.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/elekis/Desktop/Github/CPod/node_modules/dbus',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
Package dbus-1 was not found in the pkg-config search path.
Perhaps you should add the directory containing `dbus-1.pc'
to the PKG_CONFIG_PATH environment variable
No package 'dbus-1' found
gyp: Call to 'pkg-config --cflags-only-I dbus-1 | sed s/-I//g' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:259:16)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Darwin 21.1.0
gyp ERR! command \"/usr/local/bin/node\" \"/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js\" \"configure\" \"build\"
gyp ERR! cwd /Users/elekis/Desktop/Github/CPod/node_modules/dbus
gyp ERR! node -v v14.15.1
[1/4] ⠠ fsevents
[2/4] ⠠ electron
[3/4] ⠠ node-sass
error /Users/elekis/Desktop/Github/CPod/node_modules/node-sass: Command failed.
Exit code: 1
Command: node scripts/build.js
Arguments: 
Directory: /Users/elekis/Desktop/Github/CPod/node_modules/node-sass
Output:
Building: /usr/local/bin/node /Users/elekis/Desktop/Github/CPod/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   '/usr/local/bin/node',
gyp verb cli   '/Users/elekis/Desktop/Github/CPod/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.6.2
gyp info using node@14.15.1 | darwin | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "/usr/local/opt/python@3.9/bin/python3" in the PATH
gyp verb `which` succeeded /usr/local/opt/python@3.9/bin/python3 /usr/local/opt/python@3.9/bin/python3
gyp verb check python version `/usr/local/opt/python@3.9/bin/python3 -c "import platform; print(platform.python_version());"` returned: "3.9.9\n"
gyp ERR! configure error 
gyp ERR! stack Error: Python executable "/usr/local/opt/python@3.9/bin/python3" is v3.9.9, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at PythonFinder.failPythonVersion (/Users/elekis/Desktop/Github/CPod/node_modules/node-gyp/lib/configure.js:492:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/Users/elekis/Desktop/Github/CPod/node_modules/node-gyp/lib/configure.js:474:14)
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:299:7)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at maybeClose (internal/child_process.js:1048:16)
gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:439:11)
gyp ERR! stack     at Socket.emit (events.js:315:20)
gyp ERR! stack     at Pipe.<anonymous> (net.js:673:12)
gyp ERR! System Darwin 21.1.0
gyp ERR! command "/usr/local/bin/node" "/Users/elekis/Desktop/Github/CPod/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /Users/elekis/Desktop/Github/CPod/node_modules/node-sass
gyp ERR! node -v v14.15.1
gyp ERR! node-gyp -v v3.6.2

warning Error running install script for optional dependency: "/Users/elekis/Desktop/Github/CPod/node_modules/fsevents: Command failed.
Exit code: 1
Command: node install
Arguments: 
Directory: /Users/elekis/Desktop/Github/CPod/node_modules/fsevents
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.12.0
node-pre-gyp info using node@14.15.1 | darwin | x64
node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp info check checked for \"/Users/elekis/Desktop/Github/CPod/node_modules/fsevents/lib/binding/Release/node-v83-darwin-x64/fse.node\" (not found)
node-pre-gyp http GET https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.8/fse-v1.2.8-node-v83-darwin-x64.tar.gz
node-pre-gyp http 404 https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.8/fse-v1.2.8-node-v83-darwin-x64.tar.gz
node-pre-gyp WARN Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.8/fse-v1.2.8-node-v83-darwin-x64.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for fsevents@1.2.8 and node@14.15.1 (node-v83 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp http 404 status code downloading tarball https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.8/fse-v1.2.8-node-v83-darwin-x64.tar.gz 
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@14.15.1 | darwin | x64
gyp info ok 
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@14.15.1 | darwin | x64
gyp ERR! configure error 
gyp ERR! stack Error: Python executable \"/usr/local/opt/python@3.9/bin/python3\" is v3.9.9, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at PythonFinder.failPythonVersion (/Users/elekis/Desktop/Github/CPod/node_modules/node-gyp/lib/configure.js:492:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/Users/elekis/Desktop/Github/CPod/node_modules/node-gyp/lib/configure.js:474:14)
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:299:7)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at maybeClose (internal/child_process.js:1048:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
gyp ERR! System Darwin 21.1.0
gyp ERR! command \"/usr/local/bin/node\" \"/Users/elekis/Desktop/Github/CPod/node_modules/node-gyp/bin/node-gyp.js\" \"configure\" \"--fallback-to-build\" \"--module=/Users/elekis/Desktop/Github/CPod/node_modules/fsevents/lib/binding/Release/node-v83-darwin-x64/fse.node\" \"--module_name=fse\" \"--module_path=/Users/elekis/Desktop/Github/CPod/node_modules/fsevents/lib/binding/Release/node-v83-darwin-x64\" \"--napi_version=7\" \"--node_abi_napi=napi\" \"--napi_build_version=0\" \"--node_napi_label=node-v83\" \"--python=/usr/local/opt/python@3.9/bin/python3\"
gyp ERR! cwd /Users/elekis/Desktop/Github/CPod/node_modules/fsevents
gyp ERR! node -v v14.15.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /Users/elekis/Desktop/Github/CPod/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/elekis/Desktop/Github/CPod/node_modules/fsevents/lib/binding/Release/node-v83-darwin-x64/fse.node --module_name=fse --module_path=/Users/elekis/Desktop/Github/CPod/node_modules/fsevents/lib/binding/Release/node-v83-darwin-x64 --napi_version=7 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83 --python=/usr/local/opt/python@3.9/bin/python3' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/elekis/Desktop/Github/CPod/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1048:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
node-pre-gyp ERR! System Darwin 21.1.0
node-pre-gyp ERR! command \"/usr/local/bin/node\" \"/Users/elekis/Desktop/Github/CPod/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp\" \"install\" \"--fallback-to-build\"
node-pre-gyp ERR! cwd /Users/elekis/Desktop/Github/CPod/node_modules/fsevents
node-pre-gyp ERR! node -v v14.15.1
node-pre-gyp ERR! node-pre-gyp -v v0.12.0
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /Users/elekis/Desktop/Github/CPod/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/elekis/Desktop/Github/CPod/node_modules/fsevents/lib/binding/Release/node-v83-darwin-x64/fse.node --module_name=fse --module_path=/Users/elekis/Desktop/Github/CPod/node_modules/fsevents/lib/binding/Release/node-v83-darwin-x64 --napi_version=7 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83 --python=/usr/local/opt/python@3.9/bin/python3' (1)"
info This module is OPTIONAL, you can safely ignore this error

========================
if I tape gulp

elekis@mydsz:~/Desktop/Github/CPod$ gulp 
gulp[16796]: ../src/node_contextify.cc:676:static void node::contextify::ContextifyScript::New(const FunctionCallbackInfo<v8::Value> &): Assertion `args[1]->IsString()' failed.
 1: 0x1012e2bc5 node::Abort() (.cold.1) [/usr/local/bin/node]
 2: 0x1000a5cb9 node::Abort() [/usr/local/bin/node]
 3: 0x1000a5b21 node::Assert(node::AssertionInfo const&) [/usr/local/bin/node]
 4: 0x1000994db node::contextify::ContextifyScript::New(v8::FunctionCallbackInfo<v8::Value> const&) [/usr/local/bin/node]
 5: 0x100259878 v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo) [/usr/local/bin/node]
 6: 0x100258b2c v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<true>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) [/usr/local/bin/node]
 7: 0x10025850f v8::internal::Builtin_Impl_HandleApiCall(v8::internal::BuiltinArguments, v8::internal::Isolate*) [/usr/local/bin/node]
 8: 0x100a796d9 Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_BuiltinExit [/usr/local/bin/node]
 9: 0x100a0eb21 Builtins_JSBuiltinsConstructStub [/usr/local/bin/node]
10: 0x100af7263 Builtins_ConstructHandler [/usr/local/bin/node]
11: 0x100a129a2 Builtins_InterpreterEntryTrampoline [/usr/local/bin/node]
12: 0x100a129a2 Builtins_InterpreterEntryTrampoline [/usr/local/bin/node]
13: 0x100a129a2 Builtins_InterpreterEntryTrampoline [/usr/local/bin/node]
Abort trap: 6

==========
and if I tape yarn start, I have a white screen

elekis@mydsz:~/Desktop/Github/CPod$ yarn start
yarn run v1.22.17
warning ../../../package.json: No license field
$ electron .
Looks like config dir already exists, continuing
Using default settings file: /Users/elekis/Desktop/Github/CPod/public/default_settings.json
Using user settings file: /Users/elekis/Library/Application Support/cumulonimbus/user_settings.json
Loaded default settings.
Could not load user settings.
Checking for update
Error: Error: ENOENT: no such file or directory, open '/Users/elekis/Desktop/Github/CPod/dev-app-update.yml'
    at /Users/elekis/Desktop/Github/CPod/node_modules/electron-updater/src/AppUpdater.ts:370:27
    at Generator.next (<anonymous>)
From previous event:
    at MacUpdater.loadUpdateConfig (/Users/elekis/Desktop/Github/CPod/node_modules/electron-updater/out/AppUpdater.js:395:11)
    at Lazy.AppUpdater.configOnDisk.Lazy (/Users/elekis/Desktop/Github/CPod/node_modules/electron-updater/src/AppUpdater.ts:132:43)
    at Lazy.get value [as value] (/Users/elekis/Desktop/Github/CPod/node_modules/lazy-val/src/main.ts:18:23)
    at /Users/elekis/Desktop/Github/CPod/node_modules/electron-updater/src/AppUpdater.ts:281:46
    at Generator.next (<anonymous>)
From previous event:
    at MacUpdater.doCheckForUpdates (/Users/elekis/Desktop/Github/CPod/node_modules/electron-updater/out/AppUpdater.js:353:11)
    at /Users/elekis/Desktop/Github/CPod/node_modules/electron-updater/src/AppUpdater.ts:264:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at MacUpdater._checkForUpdates (/Users/elekis/Desktop/Github/CPod/node_modules/electron-updater/out/AppUpdater.js:307:11)
    at MacUpdater.checkForUpdates (/Users/elekis/Desktop/Github/CPod/node_modules/electron-updater/src/AppUpdater.ts:213:35)
    at Object.<anonymous> (/Users/elekis/Desktop/Github/CPod/main.js:301:13)
    at Object.<anonymous> (/Users/elekis/Desktop/Github/CPod/main.js:413:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at loadApplicationPackage (/Users/elekis/Desktop/Github/CPod/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar/main.js:287:12)
    at Object.<anonymous> (/Users/elekis/Desktop/Github/CPod/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar/main.js:328:5)
    at Object.<anonymous> (/Users/elekis/Desktop/Github/CPod/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar/main.js:365:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Object.<anonymous> (/Users/elekis/Desktop/Github/CPod/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/init.js:186:8)
    at Object.<anonymous> (/Users/elekis/Desktop/Github/CPod/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/init.js:188:3)
Auto-update error:
{ Error: ENOENT: no such file or directory, open '/Users/elekis/Desktop/Github/CPod/dev-app-update.yml'
    at /Users/elekis/Desktop/Github/CPod/node_modules/electron-updater/src/AppUpdater.ts:370:27
    at Generator.next (<anonymous>)
From previous event:
    at MacUpdater.loadUpdateConfig (/Users/elekis/Desktop/Github/CPod/node_modules/electron-updater/out/AppUpdater.js:395:11)
    at Lazy.AppUpdater.configOnDisk.Lazy (/Users/elekis/Desktop/Github/CPod/node_modules/electron-updater/src/AppUpdater.ts:132:43)
    at Lazy.get value [as value] (/Users/elekis/Desktop/Github/CPod/node_modules/lazy-val/src/main.ts:18:23)
    at /Users/elekis/Desktop/Github/CPod/node_modules/electron-updater/src/AppUpdater.ts:281:46
    at Generator.next (<anonymous>)
From previous event:
    at MacUpdater.doCheckForUpdates (/Users/elekis/Desktop/Github/CPod/node_modules/electron-updater/out/AppUpdater.js:353:11)
    at /Users/elekis/Desktop/Github/CPod/node_modules/electron-updater/src/AppUpdater.ts:264:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at MacUpdater._checkForUpdates (/Users/elekis/Desktop/Github/CPod/node_modules/electron-updater/out/AppUpdater.js:307:11)
    at MacUpdater.checkForUpdates (/Users/elekis/Desktop/Github/CPod/node_modules/electron-updater/src/AppUpdater.ts:213:35)
    at Object.<anonymous> (/Users/elekis/Desktop/Github/CPod/main.js:301:13)
    at Object.<anonymous> (/Users/elekis/Desktop/Github/CPod/main.js:413:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at loadApplicationPackage (/Users/elekis/Desktop/Github/CPod/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar/main.js:287:12)
    at Object.<anonymous> (/Users/elekis/Desktop/Github/CPod/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar/main.js:328:5)
    at Object.<anonymous> (/Users/elekis/Desktop/Github/CPod/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar/main.js:365:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Object.<anonymous> (/Users/elekis/Desktop/Github/CPod/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/init.js:186:8)
    at Object.<anonymous> (/Users/elekis/Desktop/Github/CPod/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/init.js:188:3)
  cause: 
   { Error: ENOENT: no such file or directory, open '/Users/elekis/Desktop/Github/CPod/dev-app-update.yml'
     errno: -2,
     code: 'ENOENT',
     syscall: 'open',
     path: '/Users/elekis/Desktop/Github/CPod/dev-app-update.yml' },
  isOperational: true,
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/elekis/Desktop/Github/CPod/dev-app-update.yml' }

How to compile the last version of CPod ?

**Comment by z-------------** [comment]
I see two possible problems from the attached log:

* Node version 14.15.1 is being used, but there has been a [report](https://github.com/z-------------/CPod/pull/145) that compilation fails with newer versions of Node. Please try using Node 8.

* gyp wants Python 2 but Python 3 is being used:

```
gyp ERR! stack Error: Python executable "/usr/local/opt/python@3.9/bin/python3" is v3.9.9, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
```

**Comment by mikenrafter** [comment]
Side-note @e471wo please use a paste service for long log messages. This makes troubleshooting far nicer.
