### ISSUE TITLE
Try to syncronize subscribed podcasts but no new episodes are updated/added

### ISSUE THREAD

**Issue by DrAxelbauer** [z-------------/CPod#255]
Hi there!
Cpod seems to be a pretty cool application! 

The following persisting problem occurs on my system:
1. Subscribed some podcast
2. Waited some weeks
3. Tried to update the subscribed podcasts
4. No new episodes are showing up

Expected: New episodes are added to the podcasts

Tried to  set some special permissions via flatseal, but that did not help. Tried to readd the podcasts but that didn't help either.

CPod v1.28.0

CPod                      com.github.z.Cumulonimbus     1.28.0         stable      flathub         system

Distributor ID: Ubuntu
Description:    Ubuntu 22.04.1 LTS
Release:        22.04
Codename:       jammy

`/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=cpod --file-forwarding com.github.z.Cumulonimbus @@u %U @@
Looks like config dir already exists, continuing
Using default settings file: /app/bin/resources/app.asar/public/default_settings.json
Using user settings file: /home/benji/.var/app/com.github.z.Cumulonimbus/config/cumulonimbus/user_settings.json
Loaded default settings.
Updating setting in main: keyboardShortcuts: {"alt+left":"skip-backward","alt+right":"skip-forward","j":"skip-backward","k":"playpause","l":"skip-forward"} --> {"alt+left":"skip-backward","alt+right":"skip-forward","j":"skip-backward","k":"playpause","l":"skip-forward"}
Updating setting in main: darkMode: false --> true
Updating setting in main: locale: undefined --> "de"
Updating setting in main: syncDeviceID: undefined --> "Benjis-Slimbook-CPod"
Updating setting in main: downloadDirectory: undefined --> "/media/benji/Storage/Downloads"
Checking for update
Error: Error: ENOENT: no such file or directory, open '/app/bin/resources/app-update.yml'
    at /app/bin/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:370:27
    at Generator.next (<anonymous>)
From previous event:
    at AppImageUpdater.loadUpdateConfig (/app/bin/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:395:11)
    at Lazy.AppUpdater.configOnDisk.Lazy (/app/bin/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:132:43)
    at Lazy.get value [as value] (/app/bin/resources/app.asar/node_modules/lazy-val/src/main.ts:18:23)
    at /app/bin/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:281:46
    at Generator.next (<anonymous>)
From previous event:
    at AppImageUpdater.doCheckForUpdates (/app/bin/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:353:11)
    at /app/bin/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:264:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at AppImageUpdater._checkForUpdates (/app/bin/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:307:11)
    at AppImageUpdater.checkForUpdates (/app/bin/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:213:35)
    at Object.<anonymous> (/app/bin/resources/app.asar/main.js:301:13)
    at Object.<anonymous> (/app/bin/resources/app.asar/main.js:413:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Object.<anonymous> (/app/bin/resources/electron.asar/browser/init.js:186:8)
    at Object.<anonymous> (/app/bin/resources/electron.asar/browser/init.js:188:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Function.Module.runMain (module.js:683:10)
    at startup (bootstrap_node.js:196:16)
    at bootstrap_node.js:622:3
Auto-update error:
{ Error: ENOENT: no such file or directory, open '/app/bin/resources/app-update.yml'
    at /app/bin/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:370:27
    at Generator.next (<anonymous>)
From previous event:
    at AppImageUpdater.loadUpdateConfig (/app/bin/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:395:11)
    at Lazy.AppUpdater.configOnDisk.Lazy (/app/bin/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:132:43)
    at Lazy.get value [as value] (/app/bin/resources/app.asar/node_modules/lazy-val/src/main.ts:18:23)
    at /app/bin/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:281:46
    at Generator.next (<anonymous>)
From previous event:
    at AppImageUpdater.doCheckForUpdates (/app/bin/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:353:11)
    at /app/bin/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:264:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at AppImageUpdater._checkForUpdates (/app/bin/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:307:11)
    at AppImageUpdater.checkForUpdates (/app/bin/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:213:35)
    at Object.<anonymous> (/app/bin/resources/app.asar/main.js:301:13)
    at Object.<anonymous> (/app/bin/resources/app.asar/main.js:413:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Object.<anonymous> (/app/bin/resources/electron.asar/browser/init.js:186:8)
    at Object.<anonymous> (/app/bin/resources/electron.asar/browser/init.js:188:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Function.Module.runMain (module.js:683:10)
    at startup (bootstrap_node.js:196:16)
    at bootstrap_node.js:622:3
  cause: 
   { Error: ENOENT: no such file or directory, open '/app/bin/resources/app-update.yml'
     errno: -2,
     code: 'ENOENT',
     syscall: 'open',
     path: '/app/bin/resources/app-update.yml' },
  isOperational: true,
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/app/bin/resources/app-update.yml' }`

**Comment by DrAxelbauer** [comment]
Just found this workaround which works for the given issue. But still it is a bug and should be fixed...
[https://github.com/z-------------/CPod/issues/196#issuecomment-734332498](https://github.com/z-------------/CPod/issues/196#issuecomment-734332498)
