### ISSUE TITLE
CPod crashes (segfault) when clicking on 'Search' text input box

### ISSUE THREAD

**Issue by w1lford** [z-------------/CPod#92]
**CPod version:**
CPod v1.25.7
**Platform:**
Linux Mint x64
**Description:**
When clicking on the text info box for CPod to search for a Podcast, CPod crashes with a segfault.
**Did the bug only start to occur after a CPod update? Version before, version after:**
Did not update CPod. Installed latest version from the Snap store.
**Steps to reproduce:**
1. Start CPod.
2. Click on the Explore tab. 
3. Click on the 'Search' text input box
**Please also attach information that might help, e.g. screenshots of console log, if possible.**
Full console log:

> no user settings file
Checking for update
Error: Error: ENOENT: no such file or directory, open '/snap/cumulonimbus/50/opt/CPod/resources/app-update.yml'
    at /snap/cumulonimbus/50/opt/CPod/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:370:27
    at Generator.next (<anonymous>)
From previous event:
    at AppImageUpdater.loadUpdateConfig (/snap/cumulonimbus/50/opt/CPod/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:395:11)
    at Lazy.AppUpdater.configOnDisk.Lazy (/snap/cumulonimbus/50/opt/CPod/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:132:43)
    at Lazy.get value [as value] (/snap/cumulonimbus/50/opt/CPod/resources/app.asar/node_modules/lazy-val/src/main.ts:18:23)
    at /snap/cumulonimbus/50/opt/CPod/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:281:46
    at Generator.next (<anonymous>)
From previous event:
    at AppImageUpdater.doCheckForUpdates (/snap/cumulonimbus/50/opt/CPod/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:353:11)
    at /snap/cumulonimbus/50/opt/CPod/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:264:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at AppImageUpdater._checkForUpdates (/snap/cumulonimbus/50/opt/CPod/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:307:11)
    at AppImageUpdater.checkForUpdates (/snap/cumulonimbus/50/opt/CPod/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:213:35)
    at Object.<anonymous> (/snap/cumulonimbus/50/opt/CPod/resources/app.asar/main.js:130:13)
    at Object.<anonymous> (/snap/cumulonimbus/50/opt/CPod/resources/app.asar/main.js:244:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Object.<anonymous> (/snap/cumulonimbus/50/opt/CPod/resources/electron.asar/browser/init.js:186:8)
    at Object.<anonymous> (/snap/cumulonimbus/50/opt/CPod/resources/electron.asar/browser/init.js:188:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Function.Module.runMain (module.js:683:10)
    at startup (bootstrap_node.js:196:16)
    at bootstrap_node.js:622:3
There was a problem updating the application
{ Error: ENOENT: no such file or directory, open '/snap/cumulonimbus/50/opt/CPod/resources/app-update.yml'
    at /snap/cumulonimbus/50/opt/CPod/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:370:27
    at Generator.next (<anonymous>)
From previous event:
    at AppImageUpdater.loadUpdateConfig (/snap/cumulonimbus/50/opt/CPod/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:395:11)
    at Lazy.AppUpdater.configOnDisk.Lazy (/snap/cumulonimbus/50/opt/CPod/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:132:43)
    at Lazy.get value [as value] (/snap/cumulonimbus/50/opt/CPod/resources/app.asar/node_modules/lazy-val/src/main.ts:18:23)
    at /snap/cumulonimbus/50/opt/CPod/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:281:46
    at Generator.next (<anonymous>)
From previous event:
    at AppImageUpdater.doCheckForUpdates (/snap/cumulonimbus/50/opt/CPod/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:353:11)
    at /snap/cumulonimbus/50/opt/CPod/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:264:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at AppImageUpdater._checkForUpdates (/snap/cumulonimbus/50/opt/CPod/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:307:11)
    at AppImageUpdater.checkForUpdates (/snap/cumulonimbus/50/opt/CPod/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:213:35)
    at Object.<anonymous> (/snap/cumulonimbus/50/opt/CPod/resources/app.asar/main.js:130:13)
    at Object.<anonymous> (/snap/cumulonimbus/50/opt/CPod/resources/app.asar/main.js:244:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Object.<anonymous> (/snap/cumulonimbus/50/opt/CPod/resources/electron.asar/browser/init.js:186:8)
    at Object.<anonymous> (/snap/cumulonimbus/50/opt/CPod/resources/electron.asar/browser/init.js:188:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Function.Module.runMain (module.js:683:10)
    at startup (bootstrap_node.js:196:16)
    at bootstrap_node.js:622:3
  cause: 
   { Error: ENOENT: no such file or directory, open '/snap/cumulonimbus/50/opt/CPod/resources/app-update.yml'
     errno: -2,
     code: 'ENOENT',
     syscall: 'open',
     path: '/snap/cumulonimbus/50/opt/CPod/resources/app-update.yml' },
  isOperational: true,
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/snap/cumulonimbus/50/opt/CPod/resources/app-update.yml' }
Unhandled rejection Error: ENOENT: no such file or directory, open '/snap/cumulonimbus/50/opt/CPod/resources/app-update.yml'
    at /snap/cumulonimbus/50/opt/CPod/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:370:27
    at Generator.next (<anonymous>)
From previous event:
    at AppImageUpdater.loadUpdateConfig (/snap/cumulonimbus/50/opt/CPod/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:395:11)
    at Lazy.AppUpdater.configOnDisk.Lazy (/snap/cumulonimbus/50/opt/CPod/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:132:43)
    at Lazy.get value [as value] (/snap/cumulonimbus/50/opt/CPod/resources/app.asar/node_modules/lazy-val/src/main.ts:18:23)
    at /snap/cumulonimbus/50/opt/CPod/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:281:46
    at Generator.next (<anonymous>)
From previous event:
    at AppImageUpdater.doCheckForUpdates (/snap/cumulonimbus/50/opt/CPod/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:353:11)
    at /snap/cumulonimbus/50/opt/CPod/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:264:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at AppImageUpdater._checkForUpdates (/snap/cumulonimbus/50/opt/CPod/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:307:11)
    at AppImageUpdater.checkForUpdates (/snap/cumulonimbus/50/opt/CPod/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:213:35)
    at Object.<anonymous> (/snap/cumulonimbus/50/opt/CPod/resources/app.asar/main.js:130:13)
    at Object.<anonymous> (/snap/cumulonimbus/50/opt/CPod/resources/app.asar/main.js:244:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Object.<anonymous> (/snap/cumulonimbus/50/opt/CPod/resources/electron.asar/browser/init.js:186:8)
    at Object.<anonymous> (/snap/cumulonimbus/50/opt/CPod/resources/electron.asar/browser/init.js:188:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Function.Module.runMain (module.js:683:10)
    at startup (bootstrap_node.js:196:16)
    at bootstrap_node.js:622:3
Segmentation fault (core dumped)

**Comment by w1lford** [comment]
One additional data point: I cloned and built CPod directly from the source and I don't get a segfault when clicking the search bar.

**Comment by z-------------** [comment]
This looks like it could be related to #83, and that one was closed when the submitter downgraded to CPod v1.25.5. So it looks like this could be an Electron issue, since CPod v1.25.5 has Electron v2.0.0 while newer versions have v2.0.8. Could you try CPod v1.25.5 (not from source) and let me know if the issue persists? Thanks.

**Comment by w1lford** [comment]
I tried v1.25.5 (appimage variant) and everything worked normally.

**Comment by z-------------** [comment]
[Here's a new (pre-)release (1.26.0)](https://github.com/z-------------/CPod/releases/tag/v1.26.0) that downgrades to Electron v2.0.0 and adds features and fixes.

**Comment by w1lford** [comment]
The issue is resolved in this version. I installed the.deb package variant of it though. The issue may have something to do with Snap instead.

**Comment by z-------------** [comment]
That may be the case, but the only builds I produce are here on GitHub Releases and the Snap version is not supported.

Regarding the search issue, could you let me know:
* Are there any errors in the console (Settings -> scroll to bottom -> Open developer tools -> Console)? If so, please attach a screenshot.
* Does the selection input to the top right of the search display anything initially (i.e. not within the dropdown list)?
* When attempting a search, does the results list stay empty or does a "No results" appear?
